<a href="https://colab.research.google.com/github/balanagavinay/sample/blob/main/CB_EN_U4CSE20136_ML_NUMPY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.shape)
print(arr.ndim)

[1 2 3 4 5]
(5,)
1


In [3]:
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
arr1 = np.array(42)
print(arr1)
print(arr1.shape)
print(arr1.ndim)

42
()
0


In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)

[[1 2 3]
 [4 5 6]]
(2, 3)
2


In [6]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr3)
print(arr3.shape)
print(arr3.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
(2, 2, 3)
3


In [7]:
print(arr1, arr[0], arr2[0][1], arr3[0][1][2])

42 1 2 6


In [8]:
print(arr1, arr[0], arr2[0, 1], arr3[0, 1, 2])

42 1 2 6


In [9]:
print(arr2)
print(arr2[-2, -1])

[[1 2 3]
 [4 5 6]]
3


In [10]:
arr4 = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr4[1:5])
print(arr4[-5:-1])
print(arr4[2:])
print(arr4[:4])
print(arr4[0:7:2])
print(arr4[::2])

[2 3 4 5]
[3 4 5 6]
[3 4 5 6 7]
[1 2 3 4]
[1 3 5 7]
[1 3 5 7]


In [16]:
arr6 = np.array(['apple', 'banana', 'cherry'])
print(arr6.dtype)

<U6


In [17]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [19]:
arr = np.array([3.47, 2.141, 4.15])
newarr = arr.astype('i')
print(newarr)
print(newarr.dtype)

[3 2 4]
int32


In [20]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [21]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

x[0] = 125
print(arr)

[42  2  3  4  5]
[42  2  3  4  5]
[125   2   3   4   5]


In [22]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

x[0] = 125
print(arr)


[42  2  3  4  5]
[42  2  3  4  5]
[125   2   3   4   5]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3
(2, 3, 2)


In [24]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)
print(newarr.ndim)
print(newarr.shape)

[1 2 3 4 5 6]
1
(6,)


In [25]:
# Iterating Arrays - 1D
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [26]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)


[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [27]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

for x in arr:
  for y in x:
    print(y)

for x in arr:
  for y in x:
    for z in y:
      print(z)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]
1
2
3
4
5
6
7
8
9
10
11
12


In [28]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [29]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
newarr = np.array_split(arr, 3)
print(newarr)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[array([1, 2, 3]), array([4, 5]), array([6, 7])]
[1 2 3]
[4 5]
[6 7]


In [30]:
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

arr1 = np.array(['banana', 'cherry', 'apple'])
print(np.sort(arr1))

arr2 = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(arr2))

[0 1 2 3]
['apple' 'banana' 'cherry']
[[2 3 4]
 [0 1 5]]


In [31]:
from numpy import random

x = random.randint(100)
print(x)

x1 = random.rand()
print(x1)

x2 = random.randint(100, size=(3, 5))
print(x2)

x3 = random.rand(3, 5)
print(x3)

69
0.17288297664480767
[[78 26 31 19 73]
 [40 27 48  3 54]
 [80 46 83 63 74]]
[[0.25913066 0.6681397  0.39536579 0.45711592 0.20494538]
 [0.31556072 0.9321604  0.37629507 0.27770326 0.03408509]
 [0.47844623 0.73362642 0.45890041 0.83652709 0.97410535]]


In [32]:
x = random.normal(size=(2, 3))
print(x)

y = random.normal(loc=1, scale=2, size=(2, 3))
print(y)

[[ 1.09390347  0.72672241  1.42613313]
 [-0.11396711 -1.61077743  1.28051791]]
[[ 1.11264998  1.18249668  1.55187174]
 [ 1.81403559  2.682932   -0.90931046]]
