<a href="https://colab.research.google.com/github/balanagavinay/sample/blob/main/CB_EN_U4CSE20136_ASS1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
sett = {"aman", "222", 777, 400.4}
tuplee = tuple(sett)
print(tuplee)

('aman', 777, '222', 400.4)


In [2]:
dict1 = {"Roll Number": "CB.EN.U4CSE20136","Last Name": "vinay","First Name": "KBN","DOB": "01-05-2002"}
print(dict1)

{'Roll Number': 'CB.EN.U4CSE20136', 'Last Name': 'vinay', 'First Name': 'KBN', 'DOB': '01-05-2002'}


In [3]:
import numpy as np
from numpy import random
arr = random.randint(0,1,size = (2,2))
print(arr)

[[0 0]
 [0 0]]


In [4]:
abs(-1234)

1234

In [5]:
print(random.random())

0.7825430240164591


In [6]:
print(random.randint(20,90))

87


In [11]:
set1 = set([11,12,13,14,15])
set2 = random.choices(list(set1),k=3)
print(set2)

[13, 13, 11]


In [9]:
import random
Set1 = set([11, 12, 13, 14, 15])
UpdatedList = random.choices(list(Set1), k = 3)
print(UpdatedList)
set2 = random.choice(list(Set1))
print(set2)

[12, 11, 11]
14


In [10]:
import os
os.getcwd()
os.chdir(r"/content/sample_data")
os.mkdir('document1')
os.chdir('document1')
f = open('document_1.txt','w+')
f.write('The King is Dead, Long Live The King')
f.seek(0)
print(f.read())
f.close()

The King is Dead, Long Live The King


In [12]:
string = 'The King is Dead, Long Live The King'
print(string)
print(string[0])
print(string[3:6])
print(string[3:])
str = string.split()
print(str)

The King is Dead, Long Live The King
T
 Ki
 King is Dead, Long Live The King
['The', 'King', 'is', 'Dead,', 'Long', 'Live', 'The', 'King']


In [14]:
import numpy as np
l=[10,67,89,35]
arr=np.array(l)
print("The first and second elements are",arr[0],arr[1])  

The first and second elements are 10 67


In [13]:
arr=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print(arr)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [16]:
arr=np.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])
print("Second Row",arr[1:][:])
print("Second Col",arr[1:,1])
print("Length of the array :",len(arr))


Second Row [[4. 5. 6.]
 [7. 8. 9.]]
Second Col [5. 8.]
Length of the array : 3


In [18]:
list3=[]
for i in range(10):
  list3.append(np.random.randint(0,100))
oned=np.array(list3)
print("1D array :",oned)
twod=oned.reshape(5,2)
print("2D array :\n",twod)
print("Transpose :\n",twod.T)

1D array : [31 47 65 23 57 63 14 60 52 89]
2D array :
 [[31 47]
 [65 23]
 [57 63]
 [14 60]
 [52 89]]
Transpose :
 [[31 65 57 14 52]
 [47 23 63 60 89]]


In [19]:
l1=[1,2,3]
l2=[1,2,3]
l3=[1,2,3]
newarr=np.array([l1,l2,l3])
print(newarr)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [20]:
arr=np.array([1,2,3])
for i in range(len(arr)):
  arr[i]=9
print(arr)

[9 9 9]


In [21]:
arr=np.array([2,4,5])
sum=0
for i in arr:
  sum+=i
print(sum)

11


In [22]:
arr=np.array([77,74,75])
prod=1
for i in arr:
  prod*=i
print(prod)

427350


In [23]:
arr=np.array([2,1,9,1,2,22,1,1,4,55,6,2,56])
print(np.mean(arr))
print(np.var(arr))
print(np.max(arr))
print(np.min(arr))
print(np.argmin(arr))
print(np.median(arr))
print(np.argmax(arr))
print(np.std(arr))

12.461538461538462
367.32544378698225
56
1
1
2.0
12
19.165736192147232


In [26]:
arr=np.array([1, 1, 7, 5, 5, 5, 4])
temp=np.array(np.unique(arr))
temp.sort()
print(temp)

[1 4 5 7]


In [24]:
x=np.array([1,2,3])
y=np.array([0,1,1])
print(np.dot(x,y))

5


In [25]:
import numpy as np
from numpy.linalg import eig
a = np.array([[2, -12], 
              [1, -5]])
w,v=eig(a)
print(w)
print(v)

[-1. -2.]
[[0.9701425  0.9486833 ]
 [0.24253563 0.31622777]]
